services:
  - type: web
    name: jaljala-school-website
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn school_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: school_project.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: *
      - key: DATABASE_URL
        fromDatabase:
          name: school-db
          property: connectionString
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: school-db
    databaseName: school_db
    user: school_user
    plan: free