# Generated by Django 6.1 on 2026-08-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_admission_contact_enhancements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admission Application', 'verbose_name_plural': 'Admission Applications'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
